version: '3'

services:

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: jlapp
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: MongoDB2019!
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    networks:
      - mongo-compose-network-v2
    deploy:
      resources: 
        limits:
          cpus: '0.50'
          memory: 256M

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - mongo-volume-v2:/data/db
    networks:
      - mongo-compose-network-v2
    deploy:
      resources: 
        limits:
          cpus: '0.50'
          memory: 256M
          
#  rabbitmq:
#    image: rabbitmq:3-management
#    environment:
#      RABBITMQ_DEFAULT_USER: luis
#      RABBITMQ_DEFAULT_PASS: teste123
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    deploy:
#      resources: 
#        limits:
#          cpus: '0.50'
#          memory: 256M



volumes:
  mongo-volume-v2:
    driver: local

networks:
  mongo-compose-network-v2:
    driver: bridge