version: '3'

services:

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: teste12345!
      MYSQL_DATABASE: db_producao
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste12345
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume-v2:/var/lib/mysql
    networks:
      - mysql-compose-network-v2
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
          
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: luis
      RABBITMQ_DEFAULT_PASS: teste123
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources: 
        limits:
          cpus: '0.50'
          memory: 256M



volumes:
  mysql-volume-v2:
    driver: local

networks:
  mysql-compose-network-v2:
    driver: bridge