server:
  port: 8074
  forward-headers-strategy: native
  use-forward-headers: true
  shutdown: graceful

spring:
  profiles:
    active: ${APP_PROFILE:local}
  devtools:
    add-properties: false
  main:
    allow-circular-references: true
  application:
    name: jlapp-producao
  lifecycle:
    timeout-per-shutdown-phase: 25s


management:
  security:
    enabled: false
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    show-details: always


jlapp:
  openapi:
    dev-url: http://localhost:8070
    hom-url: http://localhost:8070
    prod-url: https://localhost:8070
