#Configuracao do Server
logging:
  pattern: 
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [X-ReqID=%X{CorrelationId}] [%-5level] [%logger{70}] - %msg%n"

cors:
  origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

springdoc:
  api-docs:
    path: "/api-docs"

      
spring:
  main:
    banner-mode: "CONSOLE"   # por algum motivo tem que ser entre aspas duplas
    allow-bean-definition-overriding: true   
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
          minPoolSize: 5
          time_zone: America/Sao_Paulo
        timezone:
          default_storage: NORMALIZE_UTC
          
  rabbitmq:
    host: localhost
    port: 5672
    username: luis
    password: teste123
    virtual-host: /
    listener:
      simple:
        default-requeue-rejected: false

  datasource:
    url: jdbc:mysql://localhost:3306/db_producao?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: teste
    password: teste12345
    type: com.zaxxer.hikari.HikariDataSource
    initialize: true
    hikari:
      pool-name: ps-demo
      maximum-pool-size: 20
      max-lifetime: 1800000
      idle-timeout: 30000
    tomcat:
      initial-size: 5
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8


mq:
  queues:
    pedido:
      cozinha: pedido-cozinha-mq
    cozinha: cozinha-mq
    statuspedidos: status-pedidos-mq
  exchanges:
    direct: direct-exchange
  routing:
    key:
      pedido:
        cozinha: pedido-cozinha-key
      cozinha: cozinha-key
      statuspedidos: status-pedidos-key