apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlapp-producao-deployment
spec:
  selector:
    matchLabels:
      app: jlapp-producao
  replicas: 1
  template:
    metadata:
      labels:
        app: jlapp-producao
    spec:
      containers:
      - name: jlapp-producao
        image: testeluismatos/jlapp-producao-eks:latest
        ports:
        - containerPort: 8074
        resources:
          requests:
            cpu: 600m
            memory: 756Mi
          limits:
            cpu: 1000m
            memory: 1536Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8074
          initialDelaySeconds: 15
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8074
          initialDelaySeconds: 20
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        env:
          - name: JAVA_OPTS
            value: "-server -Xmx1536M -Xms756M -Xss128m"
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: MongoDB2019!
          - name: DB_HOST
            value: "mongodb"
          - name: DB_PORT
            value: "27017"
          - name: MONGO_DATABASE
            value: "jlapp-producao"
          - name: "MONGO_AUTHENTICATION"
            value: "admin"
          - name: "MONGO_AUTO_INDEX_CREATION"
            value: "true"
          - name: "MONGO_REPOSITORIES_TYPE"
            value: "auto"
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq-deployment
          - name: SPRING_RABBITMQ_PORT
            value: "5672"
          - name: SPRING_RABBITMQ_USERNAME
            value: luis
          - name: SPRING_RABBITMQ_PASSWORD
            value: teste123