apiVersion: apps/v1
kind: Deployment
metadata:
  name: jlapp-producao-deployment
spec:
  selector:
    matchLabels:
      app: jlapp-producao
  replicas: 1
  template:
    metadata:
      labels:
        app: jlapp-producao
    spec:
      containers:
      - name: jlapp-producao
        image: testeluismatos/jlapp-producao-eks:latest
        ports:
        - containerPort: 8074
        # resources:
        #   requests:
        #     cpu: 200m
        #     memory: 256Mi
        #   limits:
        #     cpu: 600m
        #     memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8074
          initialDelaySeconds: 15
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8074
          initialDelaySeconds: 20
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 20
        env:
          - name: JAVA_OPTS
            value: "-server -Xmx1024M -Xms512M -Xss128m -XX:+UseParallelGC -XX:MaxRAMPercentage=75 -XX:ActiveProcessorCount=2 -XX:+UnlockExperimentalVMOptions"
          - name: SPRING_RABBITMQ_HOST
            value: rabbitmq-deployment
          - name: SPRING_RABBITMQ_PORT
            value: "5672"
          - name: SPRING_RABBITMQ_USERNAME
            value: luis
          - name: SPRING_RABBITMQ_PASSWORD
            value: teste123