apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq-deployment
  template:
    metadata:
      labels:
        app: rabbitmq-deployment
    spec:
      containers:
      - name: rabbitmq-deployment
        image: rabbitmq:3-management
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: luis
        - name: RABBITMQ_DEFAULT_PASS
          value: teste123
        ports:
        - containerPort: 5672
        - containerPort: 15672
