apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jlapp-producao-deployment.yaml
  - jlapp-producao-service.yaml
  - service-account.yaml
  - hpa.yaml
  - nginx-config.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - mq/rabbitmq-deployment.yaml
  - mq/rabbitmq-service.yaml
  - Metrics/components.yaml

images:
  - name: jlapp-producao
    newName: jlapp-producao
    newTag: latest
